export const NUMBER_OF_RULES_OF_THE_ROAD_QUESTIONS = 28;
export const NUMBER_OF_ROAD_SIGNS_QUESTIONS = 28;
export const NUMBER_OF_CONTROLS_QUESTIONS = 8;
export const RULES_OF_THE_ROAD_PASSMARK = 22;
export const ROAD_SIGNS_PASSMARK = 23;
export const CONTROLS_PASSMARK = 6;