export const ON_SELECT_ANSWER = 'ON_SELECT_ANSWER';
export const ON_SUBMIT = 'ON_SUBMIT';
export const ON_PREVIOUS_QUESTION = 'ON_PREVIOUS_QUESTION';
export const ON_NEXT_QUESTION = 'ON_NEXT_QUESTION';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const START_TIMER = 'START_TIMER';